GET http://localhost:5000/users

###
# Mengakses route yang dilindungi dengan token
GET http://localhost:5000/protected-route

###
GET http://localhost:5000/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcyMjIzNjc0OCwiZXhwIjoxNzIyMjQwMzQ4fQ.kMsdri9bSw103cbjRw4vlTLFrvyxOEpRFYUiOypOWw8
###
GET http://localhost:5000/users-show/dimas@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJkaW1hczNAZ21haWwuY29tIiwiaWF0IjoxNzIzOTEwOTAwLCJleHAiOjE3MjM5MTQ1MDB9.ru5029dxDu83ccs-FTW9BzUpcsNEacw_JpIO7V1DhgM

### Logout User
POST http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcyMjIzMTUyMywiZXhwIjoxNzIyMjM1MTIzfQ.hr0JiWJBsit4qGnaEMzNe1ROU2FAewp1X9MibhlcPlo


###
GET http://localhost:5000/barang
###

POST http://localhost:5000/register
Content-Type: application/json

{
    "name" : "budi",
    "email" : "dimas3@gmail.com",
    "gender" : "pria",
    "password" : "password",
    "alamat" : "jl winongan"
}

###
PATCH  http://localhost:5000/users-update/5
Content-Type: application/json

{
    "name" : "samid",
    "email" : "dimas@gmail.com",
    "gender" : "pria",
    "password" : "password",
    "alamat" : "jl. pasuruan"
}

###
PATCH  http://localhost:5000/users-update-email/dimas@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcyMzg4MDQwNSwiZXhwIjoxNzIzODg0MDA1fQ.dK21INKCndjO27ZNpNcqHhEIbtpnyEFmztwh64OgkcY
Content-Type: application/json

{
    "name" : "budi",
    "email" : "dimas@gmail.com",
    "gender" : "pria",
    "password" : "password234",
    "alamat" : "jl. pasuruan kab pasuruan"
}

###
DELETE http://localhost:5000/users-delete/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcyMzkwMzc4OSwiZXhwIjoxNzIzOTA3Mzg5fQ.zYILqEKOHUHODCysF0EEguNS2TQaCgy5IQC68EkNmXk

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dimas3@gmail.com",
    "password": "password"
}


